name: Test Unity Activation

on:
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  test-unity-activation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Unity - Activate
        uses: game-ci/unity-activate@v2.0.0
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
